# Generated by Django 3.2.8 on 2021-10-25 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arrivals', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalarrival',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.person'),
        ),
    ]
