# Generated by Django 3.2.8 on 2021-11-08 10:39

from django.db import migrations
from faker import Faker
from faker.providers import address, person

fake = Faker()
fake.add_provider(address)
fake.add_provider(person)


def insert_arrivals(apps, schema_editor):
    AnimalArrival = apps.get_model('arrivals', 'AnimalArrival')
    User = apps.get_model('users', 'User')
    Animal = apps.get_model('animals', 'Animal')

    for _ in range(1):
        user = User.objects.filter(is_staff=True).order_by('?').first()
        animal = Animal.objects.order_by('?').first()
        first_name_of_surrender = fake.first_name()
        last_name_of_surrender = fake.last_name()
        address_of_surrender = fake.address()

        AnimalArrival.objects.create(user=user, animal=animal, last_name_of_surrender=last_name_of_surrender,
                                     first_name_of_surrender=first_name_of_surrender,
                                     address_of_surrender='Wrocław, Małowiejska 4')


class Migration(migrations.Migration):

    dependencies = [
        ('arrivals', '0002_animalarrival_user'),
        ('users', '0002_initial_data_insertion'),
    ]

    operations = [
        migrations.RunPython(insert_arrivals, migrations.RunPython.noop)
    ]
