# Generated by Django 3.2.8 on 2021-12-01 22:07

import animals.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip_code', models.CharField(max_length=50, unique=True, verbose_name='Chip Code')),
                ('name', models.CharField(max_length=50, verbose_name='Imię')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Pełnych lat')),
                ('color', models.TextField(help_text='Opisanie koloru', max_length=500, verbose_name='Kolor')),
                ('image', models.ImageField(default='animals/default.jpg', upload_to=animals.models.image_path, verbose_name='Zdjęcie')),
                ('height', models.PositiveSmallIntegerField(verbose_name='Wzrost')),
                ('weight', models.PositiveSmallIntegerField(verbose_name='Masa')),
                ('description', models.TextField(max_length=1000, null=True, verbose_name='Komentarz')),
                ('vaccinations', models.TextField(help_text='Tu opisz jakie szczepienia miało', max_length=1000, verbose_name='Szczepienia')),
            ],
            options={
                'verbose_name': 'Zwierzę',
                'verbose_name_plural': 'Zwierzęta',
            },
        ),
        migrations.CreateModel(
            name='AnimalBreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True, verbose_name='Wartość')),
            ],
            options={
                'verbose_name': 'Rasa Zwierzęcia',
                'verbose_name_plural': 'Rasy Zwierząt',
            },
        ),
        migrations.CreateModel(
            name='AnimalGender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20, unique=True, verbose_name='Wartość')),
            ],
            options={
                'verbose_name': 'Płeć Zwierzęcia',
                'verbose_name_plural': 'Płeć Zwierząt',
            },
        ),
        migrations.CreateModel(
            name='AnimalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True, verbose_name='Wartość')),
            ],
            options={
                'verbose_name': 'Status Zwierzęcia',
                'verbose_name_plural': 'Statusy Zwierząt',
            },
        ),
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True, verbose_name='Wartość')),
            ],
            options={
                'verbose_name': 'Gatunek Zwierzęcia',
                'verbose_name_plural': 'Gatunki Zwierząt',
            },
        ),
        migrations.CreateModel(
            name='AnimalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=animals.models.image_path)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='animals.animal')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='animals.animalbreed', verbose_name='Rasa Zwierzęcia'),
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='animals.animalgender', verbose_name='Płeć Zwierzęcia'),
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='animals.animalstatus', verbose_name='Status Zwierzęcia'),
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='animals.animaltype', verbose_name='Gatunek Zwierzęcia'),
        ),
    ]
