# Generated by Django 3.2.8 on 2021-10-25 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalBreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True, verbose_name='Wartość')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalGender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True, verbose_name='Wartość')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True, verbose_name='Wartość')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True, verbose_name='Wartość')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip_code', models.CharField(max_length=100, unique=True, verbose_name='Chip Code')),
                ('name', models.CharField(max_length=100, verbose_name='Imię')),
                ('age', models.IntegerField(verbose_name='Pełnych lat')),
                ('color', models.TextField(help_text='Opisanie koloru', max_length=500, verbose_name='Kolor')),
                ('height', models.IntegerField(verbose_name='Wzrost')),
                ('description', models.TextField(max_length=1000, verbose_name='Komentarz')),
                ('vaccinations', models.TextField(help_text='Tu opisz jakie szczepienia miało', max_length=1000, verbose_name='Szczepienia')),
                ('animal_breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='animals.animalbreed')),
                ('animal_gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='animals.animalgender')),
                ('animal_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='animals.animalstatus')),
                ('animal_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='animals.animaltype')),
            ],
        ),
    ]
