# Generated by Django 3.2.8 on 2021-11-07 13:40

from django.db import migrations


def insert_genders(apps, schema_editor):
    genders = ['Samiec', 'Samica', 'Brak']
    AnimalGender = apps.get_model('animals', 'AnimalGender')
    for gender in genders:
        AnimalGender.objects.create(value=gender)


def insert_statuses(apps, schema_editor):
    statuses = ['Do adopcji', 'Kwarantanna', 'Zaadoptowany', 'Zarezerwowany']
    AnimalStatus = apps.get_model('animals', 'AnimalStatus')
    for status in statuses:
        AnimalStatus.objects.create(value=status)


def insert_types(apps, schema_editor):
    types = ['Pies', 'Kot', 'Świnia', 'Królik']
    AnimalType = apps.get_model('animals', 'AnimalType')
    for type_ in types:
        AnimalType.objects.create(value=type_)


def insert_breeds(apps, schema_editor):
    breeds = ['Chihuahua', 'Niemiecki owczarek', 'Buldog']
    AnimalBreed = apps.get_model('animals', 'AnimalBreed')
    for breed in breeds:
        AnimalBreed.objects.create(value=breed)


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_genders, migrations.RunPython.noop),
        migrations.RunPython(insert_statuses, migrations.RunPython.noop),
        migrations.RunPython(insert_types, migrations.RunPython.noop),
        migrations.RunPython(insert_breeds, migrations.RunPython.noop)
    ]
