# Generated by Django 3.2.8 on 2021-11-09 00:07

import animals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_initial_data_insertion'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='image',
            field=models.ImageField(default='animals/default.jpg', upload_to=animals.models.image_path),
        ),
    ]
