# Generated by Django 3.2.8 on 2021-11-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_animal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='weight',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Waga'),
            preserve_default=False,
        ),
    ]
