# Generated by Django 3.2.8 on 2021-11-09 00:23

import animals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_animal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=animals.models.image_path),
        ),
    ]
