# Generated by Django 3.2.8 on 2021-10-25 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='person',
            new_name='user',
        ),
    ]
