# Generated by Django 3.2.8 on 2021-11-08 10:27

from django.db import migrations
from django.contrib.auth.hashers import make_password
from random import choices
from faker import Faker
from faker.providers import phone_number, address, person, internet

fake = Faker()
fake.add_provider(address)
fake.add_provider(person)
fake.add_provider(phone_number)
fake.add_provider(internet)


def insert_users(apps, schema_editor):
    User = apps.get_model('users', 'User')

    for _ in range(60):
        email = fake.email()
        first_name = fake.first_name()
        last_name = fake.last_name()
        address = fake.address()
        pesel = fake.msisdn()[:-2]
        phone = '+48' + fake.msisdn()
        password = 'password'
        is_staff = choices([True, False], weights=[0.25, 0.75])[0]

        User.objects.create(email=email, first_name=first_name, last_name=last_name, pesel=pesel,
                            is_staff=is_staff, phone=phone, address=address, password=make_password(password))


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_users, migrations.RunPython.noop)
    ]
