# Generated by Django 3.2.8 on 2021-11-09 00:07

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial_data_insertion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='users/default.jpg', upload_to=users.models.image_path),
        ),
    ]
