# Generated by Django 3.2.8 on 2021-12-01 22:07
import os

from django.db import migrations, connection


def load_data_from_sql(apps, schema_editor):
    file_path = os.path.join(os.path.dirname(__file__), '../db_scripts/Constraints.sql')
    sql_statement = open(file_path).read()
    with connection.cursor() as c:
        c.execute(sql_statement)


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_initial_data_insertion'),
        ('reservations', '0003_initial_data_insertion'),
        ('locations', '0002_initial_data_insertion'),
        ('arrivals', '0003_initial_data_insertion'),
        ('animals', '0002_initial_data_insertion'),
        ('adoptions', '0003_initial_data_insertion'),
    ]

    operations = [
        migrations.RunPython(load_data_from_sql, migrations.RunPython.noop),
    ]
